### ISSUE TITLE
CM4 Version

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/FlashStick#3]
For when you have any bandwidth @ryanteck - not urgent of course :-)

**Comment by shawaj** [comment]
@ryanteck actually just had an idea. Potentially could add on the back side of the CM3 PCB the connectors for the CM4

Then a single board can do both Cm1/3 and the cm4 as well.

Maybe uprate the USB to USB 3 for cm4 faster speeds or something

**Comment by ryanteck** [comment]
I think for programming USB2 is used on the CM4 too (as USB3 is provided by a PCI-E chip which isn't present on the CM4).

If it was on the back side it would increase production costs due to double sided soldering and for some not possible to solder at home if ordering boards to DIY.

**Comment by ryanteck** [comment]
I think for the CM4 the circuitry is also a lot less, I think apart from providing power and the USB pins being connected it requires nothing else.

**Comment by ryanteck** [comment]
Footprint https://github.com/shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint

**Comment by shawaj** [comment]
Was just a thought that you could kill 2 birds with one stone, for example in production environments where they program both cm3 and cm4 for things.

But yes I suppose there's merit in both - a combined one for certain environments and separate for others

**Comment by ryanteck** [comment]
Shall I do a seperate one first then possibly do a combined one if the seperate one works?

My only other concern of a combined one would be if somebody tried to put both a CM3 and CM4 in at the same time.

I can't remember if I saw either but I think somewhere I saw that the lifetime of the CM4 connectors is less so it could be that it wears out quicker being cheaper over time to replace it with just the single. Not fully sure with that though.

**Comment by ryanteck** [comment]
![Screenshot from 2021-01-18 11-30-25](https://user-images.githubusercontent.com/1104745/104909980-937c1280-5980-11eb-846e-1c6a21f915db.png)


Rough idea

**Comment by ryanteck** [comment]
I think actually the connector would be the main reason to have it seperate as if it wears down this quickly the boards might not last long.

![Screenshot from 2021-01-18 11-32-18](https://user-images.githubusercontent.com/1104745/104910178-d807ae00-5980-11eb-8138-81a7d329eed2.png)

**Comment by shawaj** [comment]
@ryanteck that's awful haha. It's like they didn't think about production environments at all. But yeah maybe start with a cm4 standalone and then do a combined one after potentially

**Comment by shawaj** [comment]
I wonder if you can get solderless USB edge connectors too.

Could be cool to have an option for the USB connector to be on the top left, bottom left as well

Like this...

![Screenshot_20210118-114810_Chrome](https://user-images.githubusercontent.com/3359418/104911638-1736fe80-5983-11eb-9647-3d4189163f16.jpg)

**Comment by ryanteck** [comment]
One where the PCB is the connector?

**Comment by shawaj** [comment]
Well - potentially - but what I was actually thinking was more like an edge connector that you could clamp a USB jack onto.

So effectively you could have 3 different locations for the USB jack that you could change between.

Similar to this, but instead of for a cable, for a PCB - https://www.aliexpress.com/i/32859840759.html

Not sure it actually exists though!!

**Comment by shawaj** [comment]
CM4 version https://github.com/NebraLtd/FlashStick/tree/main/Raspberry_Pi_Compute_Module_4

Still needs testing though so will leave this open for now

**Comment by shawaj** [comment]
Working now
